### ISSUE TITLE
Unicode 9

### ISSUE THREAD

**Issue by doublex** [adah1972/libunibreak#12]
Are there any plans to update to unicode 9?

**Comment by adah1972** [comment]
Thanks for reminding. I will have a look later.

**Comment by tasn** [comment]
I started taking a look, but I don't have time to do it today. I assumed it would be a simple update, but the Emjoi changes include a few more complex rules that I just don't have time to deal with at the moment.

Will try to take a look later this week. No promises.

**Comment by doublex** [comment]
Thanks!

**Comment by adah1972** [comment]
Actually it is only half-done...

**Comment by tasn** [comment]
I will take a look into this again today or tomorrow.
