### ISSUE TITLE
 recipe for target 'install-exec-hook' failed 

### ISSUE THREAD

**Issue by slackmart** [adah1972/libunibreak#13]
I'm trying to compile this inside a x86_64 environment and I'm getting this error:

    recipe for target 'install-exec-hook' failed 

This was introduced in 2012 as stated in the [Changelog L472](https://github.com/adah1972/libunibreak/blob/8c92b46511baf5b51457f202cf53d8602e1aef17/ChangeLog#L472)

Can this error be safely ignored?

**Comment by adah1972** [comment]
Hi Martín, I would assume so.

However, it is a bit weird. You can see that the target install-exec-hook is very simple:

```
install-exec-hook:
        - [ -f $(DESTDIR)/${libdir}/libunibreak.a ] && \
        rm -f $(DESTDIR)/${libdir}/liblinebreak.a && \
        ${LN_S} $(DESTDIR)/${libdir}/libunibreak.a $(DESTDIR)/${libdir}/liblinebreak.a
```

Can you check which line causes this problem?

**Comment by slackmart** [comment]
Hello @adah1972 , I've discussed this issue with a colleague.

Now I understand this is not a fatal error, so it can be omitted.

BTW I've learned a few things from this:
- The `-` at the begin of `- [ -f $(DESTDIR)/${libdir}/libunibreak.a ]` makes the script ignore this error and continue with the process.
- About the `rm` statement, we can either remove the `-f` if we use the conditional to verify if the file exists or just remove the conditional since we can ensure (from the man pages) that the `rm` command will ignore this if the file doesn't exists (that's precisely the error).

Reference to the man page:
```
    -f, --force
              ignore  nonexistent files and arguments, never prompt
```

**Comment by adah1972** [comment]
Hi Martín, what I do not understand is why it failed. It does the following:

1) Checks libunibreak.a exists at the target directory
2) Remove liblinebreak.a at the target directory
3) Create a link of libunibreak.a as liblinebreak.a

Did you use --enabled-static=no? That is the only reason I can think of that will cause the recipe to fail in normal circumstances.

**Comment by slackmart** [comment]
At the begin I had the `--enabled-static` option set to `no`, after I read that setting has a `yes` value as a default. I have tried switching the value and the error persist in both scenarios.

The file doesn't exists (that's throwing the error).

Cheers!

**Comment by adah1972** [comment]
If static build is enabled, the first operation (-f) should succeed. "rm -f" should not report any errors, even if the file to remove does not exist. I am very curious to know what on earth has happened. Can you report any additional error messages, and/or check whether the target libunibreak.a exists?

**Comment by slackmart** [comment]
Sorry man, actually the error is not reported by `rm -f`, but by the first line `- [ -f $(DESTDIR)/${libdir}/libunibreak.a ]`. I mean the file doesn't exists.

By the way, I'm updating a slackbuild (you know for Slackware): [libunibreak (slackbuild source)] (https://slackbuilds.org/repository/14.2/libraries/libunibreak/).
In pending status by the moment [slackbuilds pending list] (https://slackbuilds.org/pending/).

**Comment by adah1972** [comment]
That would be normal for the `--enable-static=no` case. Hard to understand otherwise.
