### ISSUE TITLE
Unicode 11

### ISSUE THREAD

**Issue by doublex** [adah1972/libunibreak#21]
This file:
https://github.com/adah1972/libunibreak/blob/master/src/wordbreak.c
Unicode 11:
http://www.unicode.org/reports/tr29/tr29-32.html

marked as obsolete:
```
E_Base
E_Modifier
Glue_After_Zwj
E_Base_GAZ
```

Added:
```
WSegSpace
```

**Comment by adah1972** [comment]
@tasn Tom, comments?

**Comment by tasn** [comment]
@adah1972, sorry, but not time to take a look at the moment, and don't think I'll have any in the immediate future. :(
Ping me again in a few weeks if you haven't managed to fix it by then?

**Comment by doublex** [comment]
Are there any plans to upgrade this great library to unicode 11?
Best wishes!

**Comment by adah1972** [comment]
@doublex I made some quick fixes. Please test and check.

**Comment by adah1972** [comment]
@roever Do you have time to check any updates are necessary in grapheme breaking?

**Comment by doublex** [comment]
@adah1972 
Great library! 
Thanks a lot!

**Comment by adah1972** [comment]
How about separating the work and doing the easy work first? We can go step by step, and every improvement is a good one. I do not feel it a problem if incorporating the emoji data table takes extra time and cannot be done right away.

**Comment by roever** [comment]
I'll do it. I don't think it will take that long...

**Comment by adah1972** [comment]
@doublex I think we have fully updated the library for Unicode 11. I have uploaded a test 4.1 release here (NEWS, configure.ac, and src/Makefile.am have uncommitted changes):

http://wyw.dcweb.cn/libunibreak-4.1.tar.gz

If you have time, please take a look. I will make a new release in about a week.

**Comment by adah1972** [comment]
Regretfully the last "RC" failed many test cases (kudos to Andreas for making all grapheme breaking tests pass). I have fixed all regression issues, and also updated the line breaking code to reduce the number of skipped/failed tests significantly.

The RC download link remains the same.

**Comment by adah1972** [comment]
I have made [release 4.1](https://github.com/adah1972/libunibreak/releases/tag/libunibreak_4_1), and am closing this issue. If there are other problems, please open a new issue.
