### ISSUE TITLE
unicode 12

### ISSUE THREAD

**Issue by roever** [adah1972/libunibreak#23]
I had a look at Unicode version 12. Seems like this time all we have to do is update the tables. No rule changes as far as I can see.

If that is the case we could quickly do a new release.

**Comment by adah1972** [comment]
I'll have a look about this weekend. Meanwhile, feel free to take actions on your part of the code.

**Comment by roever** [comment]
I created pull request #24 updating the grapheme break stuff. I checked with the upated tests, everything seems fine

**Comment by adah1972** [comment]
I have merged the PR and made other code changes. I have also updated src/Makefile.am and src/unibreakbase.h for version information locally. If no one finds a problem, I will commit those files and make a release soon.

**Comment by adah1972** [comment]
A new release is made.
