### ISSUE TITLE
Test condition is always false

### ISSUE THREAD

**Issue by SamuelMarks** [adah1972/libunibreak#27]
Looking through your code and I was confused as to how this branch could be reached:
https://github.com/adah1972/libunibreak/blob/505d035ea16a2d06ac5bb05c4e2323fb756c1728/src/tests.c#L196

Context:
https://github.com/adah1972/libunibreak/blob/505d035ea16a2d06ac5bb05c4e2323fb756c1728/src/tests.c#L183-L204

I can send through a PR to remove that branch; but wanted to verify you weren't using it for your own testing first; and that it wasn't an actual bug and you meant to handle modify that variable elsewhere.

**Comment by adah1972** [comment]
@tasn Any comment here? Do you want the branch to be removed or retained?

**Comment by adah1972** [comment]
@SamuelMarks BTW, it is wrong to state that the condition cannot reached. In fact, the condition is always true. So if Tom agrees, we will remove the condition, not the branch.

**Comment by tasn** [comment]
It's been years since I touched this code, but the question is, why did I add it in the first place?
Anyhow, from first glance, it seems OK to remove the condition (but not the branch). The code works (I guess?) so if you also can't see what this variable is for, it can probably be removed.

**Comment by SamuelMarks** [comment]
Sounds good, so I've opened this PR, which will close https://github.com/adah1972/libunibreak/pull/28 this issue

**Comment by SamuelMarks** [comment]
Closed by #28
