### ISSUE TITLE
Possible Optimization

### ISSUE THREAD

**Issue by mta452** [adah1972/libunibreak#32]
I propose to optimize the usage of memory with following points.
* Let `GRAPHEMEBREAK` values 1-3 , make `LINEBREAK` values 4-7 , and `WORDBREAK` values 8-10
* Make the client ensure initially all elements of input array are set to 0
* Allow grapheme break, line break and word break to work on a single array i.e. commutative

**Comment by adah1972** [comment]
Sorry, it does not look like a good idea to me. It will increase coupling among the code, and, besides, since the different kind breaks can happen at the same time, you need bit masks instead of allocating different values in order to allow them to work on the same array.
