### ISSUE TITLE
Provide a brief example of using your code in the readme

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [adah1972/libunibreak#33]
I would like to integrate your library into my project. However, I can't quite glean enough information from doxygen to understand how to use it. I have questions.

Rather than bore you by asking 20 questions, I thought maybe you could provide some sort of brief example in the README (and maybe the src comments?). Nothing fancy, maybe something that dumps to a console based on a few input strings, or like that.

That would be greatly appreciated. Doxygen is a wonderful tool but it only gets you so far. 

Edit: I've tinkered enough to figure out how to use it, but I still think an example would be great.

**Comment by adah1972** [comment]
I guess you may start from the examples. Places to start:

https://github.com/adah1972/libunibreak/blob/master/tools/linebreak_test.c
https://github.com/adah1972/breaktext
