### ISSUE TITLE
Fix confusion with old naming/version

### ISSUE THREAD

**Issue by tasn** [adah1972/libunibreak#8]
Hey,

I'm opening a ticket since I haven't decided what's the right thing and I'd love to get some input.
To get a tarball of the latest version, users should go here: https://github.com/adah1972/libunibreak/releases
Looking there, you can see many releases (7 at the time of writing). Two of which are releases using the new library name, and 5 using the old one. The problem is, that a user scanning the list will see strings that look very much alike, so will think they are all the same, and will look at the number thus mistakenly get liblinebreak 2.1 (old) instead of libunibreak 1.1. It almost just happened to me.

I don't know what the correct solution is, maybe it's to release libuniberak 3.0, maybe delete the old releases (pretty bad), maybe to rename the old releases to "old-liblinebreak-*" (pretty bad), or I dunno.

Thoughts?

--
Tom.

**Comment by adah1972** [comment]
I think people will probably look at the dates. However, I won't object to releasing a 3.0 version after we fix the Unicode 7.0 issue you mentioned in another message.

**Comment by tasn** [comment]
I fixed #9, feel free to release 3.0 whenever you'd like.

Our lack of regression tests (which I've mentioned in a previous ticket) kinda scares me with this release, but from what I can see, everything works as expected.

**Comment by tasn** [comment]
Hey, are we releasing 3.0? I would like to nudge arch to update to 3.0 the moment it's out. :)

They are apparently using an old version.

**Comment by adah1972** [comment]
Let me make some final touches this weekend. In the meanwhile, please help check whether there are any issues or other possible improvements.

**Comment by adah1972** [comment]
OK, 3.0 released.
